version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - 3000:80
      - 443:443
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app
    depends_on:
      - node1
      - node2
      - node3

  node1:
    image: node:latest
    ports:
      - 3001:3000
    container_name: "node1"
    volumes: 
    - ./containers/node:/usr/app/
    command: node ./usr/app/server.js
    networks:
      - app
    environment:
      - NAME_OF_NODE=node1

  node2:
    image: node:latest
    ports:
      - 3002:3000
    networks:
      - app
    container_name: "node2"
    volumes: 
      - ./containers/node:/usr/app/
    command: node ./usr/app/server.js
    environment:
      - NAME_OF_NODE=node2

  node3:
    image: node:latest
    ports:
      - 3003:3000
    networks:
      - app
    container_name: "node3"
    volumes: 
      - ./containers/node:/usr/app/
    command: node ./usr/app/server.js
    environment:
      - NAME_OF_NODE=node3

networks:
  app: