version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - 3000:80
      - 443:443
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app
    links:
      - node1:node1
      - node2:node2
      - node3:node3
    depends_on:
      - node1
      - node2
      - node3

  node1:
    build: ./containers/node
    ports:
      - 3001:3000
    container_name: "node1"
    networks:
      - app
      - db
    environment:
      - NAME_OF_NODE=node1
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
  node2:
    build: ./containers/node
    ports:
      - 3002:3000
    networks:
      - app
      - db
    container_name: "node2"
    environment:
      - NAME_OF_NODE=node2
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
  node3:
    build: ./containers/node
    ports:
      - 3003:3000
    networks:
      - app
      - db
    container_name: "node3"
    environment:
      - NAME_OF_NODE=node3
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
  couchserver:
    build: "./containers/couchdb"
    restart: always
    container_name: "bookmaster"
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    networks:
      - db
    volumes:
      - ./containers/couchdb/data:/opt/couchdb/data
networks:
  app:
  db: