version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - 3000:80
      - 443:443
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app
    depends_on:
      - node1
      - node2
      - node3

  node1:
    build: ./containers/node
    ports:
      - 3001:3000
    container_name: "node1"
    networks:
      - app
      - db
    environment:
      - NAME_OF_NODE=node1

  node2:
    build: ./containers/node
    ports:
      - 3002:3000
    networks:
      - app
      - db
    container_name: "node2"
    environment:
      - NAME_OF_NODE=node2

  node3:
    build: ./containers/node
    ports:
      - 3003:3000
    networks:
      - app
      - db
    container_name: "node3"
    environment:
      - NAME_OF_NODE=node3
    
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: "my-mongo-container"
    volumes:
      - ./containers/mongo:/data/db
      - ./containers/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
      - MONGO_INITDB_DATABASE=BookMaster
    networks:
      - db
networks:
  app:
  db: