name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DBUSER: ${{ secrets.DBUSER }}
  DBPASS: ${{ secrets.DBPASS }}
  CLIENTID: ${{ secrets.CLIENTID }}
  CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
  RABBITUSER: ${{ secrets.RABBITUSER }}
  RABBITPASS: ${{ secrets.RABBITPASS }}
  MAILUSER: ${{ secrets.MAILUSER }}
  MAILPASS: ${{ secrets.MAILPASS }}
  COUCHDB_USER: ${{ secrets.COUCHDB_USER }}
  COUCHDB_PASSWORD: ${{ secrets.COUCHDB_PASSWORD }}
  RABBITMQ_DEFAULT_USER: ${{ secrets.RABBITMQ_DEFAULT_USER }}
  RABBITMQ_DEFAULT_PASS: ${{ secrets.RABBITMQ_DEFAULT_PASS }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./containers/node
    steps:
      - name: Checkup & Setup Node
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: npm installation
        run: npm install
      - name: run test
        run: npm run test