name: test-and-deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install
      working-directory: ./app
    - run: npm test
      working-directory: ./app