name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CLIENTID: ${{ secrets.CLIENTID }}
  CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
  API_KEY : ${{secrets.API_KEY}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./containers/node
    steps:
      - name: Checkup & Setup Node
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: npm installation
        run: npm install
      - name: run test
        run: npm run test